### ISSUE TITLE
setup instructions for iOS incorrectly say to add entire RNHockeyApp folder

### ISSUE THREAD

**Issue by tomprogers** [slowpath/react-native-hockeyapp#11]
The instructions say to add the entire RNHockeyApp folder to your project.

```
Add the RNHockeyApp/ folder to your project

Drag-and-drop from ./node_modules/react-native-hockeyapp/RNHockeyApp folder to your Project > Libraries.
```

This doesn't work, at least when performed against react-native v0.20.0.

The correct procedure is to add the two files _inside_ the RNHockeyApp folder.

**Comment by iamladi** [comment]
@JBerendes Update Readme instructions so the problem you have should be solved.   Let me know if it helps.

**Comment by yoniholmes** [comment]
Hi guys, thanks for flagging this and making efforts to fix this. This still isn't clear however, even after the PR. Because the title says to `Add the RNHockeyApp/ folder to your project`, that's exactly what we did. It should read `Add 2 files from the RNHockeyApp to your project` to avoid ambiguity – if indeed that's what you're supposed to do. 

At time of writing, we haven't got this working yet. I also notice the approach for adding libraries for this module appears to be different from all other react-native plugins. Other react-native plugins have an .xcodeproj folder that gets added to the Libraries directory. Whereas for this module it appears that I'm supposed to add `RNHockeyApp.h` and `RNHockeyApp.m` directly to the Libraries directory?

Finally, no instructions are given about which settings to select when importing these to Xcode. I.e:
- Should 'Copy items if needed` be selected or not?
- Should I select `Create groups` or `Create folder references`, or does it not matter?

Any ideas on the above?

Many thanks

**Comment by iamladi** [comment]
I have released new version 0.4.0 that should work with `rnpm link`. It will do all the magic for you.

**Comment by arthurvi** [comment]
Do you mean with "all the magic" that the only steps necessary are `npm install` and `rnpm link` ?

**Comment by iamladi** [comment]
@arthurvi Yes.

**Comment by arthurvi** [comment]
@martincik Hmm, then I had to open an issue. I just don't get it working: https://github.com/slowpath/react-native-hockeyapp/issues/20
